config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'thoughts#dashboard'

  post 'thoughts' => 'thoughts#create', as: :thoughts

  get 'tags/:tag' => 'tags#show', as: :tag

end

app/models/thought.rb
class Thought < ActiveRecord::Base

  validates :content,
    presence: true,
    length: {maximum: 255},
    uniqueness: {message: "You already deep thoughted that"}

  mount_uploader :photo, PhotoUploader

  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show

    tag_name = params[:tag]

    # find all thoughts with a tag of tag_name
    @thoughts = Thought.tagged_with(tag_name)
                       .order("created_at desc")
                       .page(params[:page])

  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController

  before_action do
    @thoughts = Thought.all
                       .order("created_at desc")
                       .page(params[:page])
  end

  def dashboard
    @thought = Thought.new
  end

  def create
    @thought = Thought.new params.require(:thought).permit(:content, :photo, :tag_list)
    if @thought.save
      redirect_to root_path, notice: "Thought Added deeply"
    else
      render :dashboard
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeepThoughts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tags/show.html.erb
<h1>Tags for <%= params[:tag] %></h1>

<%= render partial: 'thoughts/thoughts' %>

app/views/thoughts/_thoughts.html.erb
<h3><%= pluralize @thoughts.total_count, "thought" %></h3>


  <% @thoughts.each do |thought| %>
    <div class="media">

    <div class="media-left">
      <%= link_to thought.photo.url(:large) do %>
        <%= image_tag thought.photo.url(:thumb), class: "media-object img-rounded"  %>
      <% end %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= auto_link thought.content %>
      </h4>
      <p>
        Posted <%= distance_of_time_in_words_to_now thought.created_at %> ago
      </p>
      <p>
        Tagged: <%= thought.tag_list.map{|tag| link_to tag, tag_path(tag: tag) }.join(", ").html_safe %>
      </p>
    </div>
  </div>
  <% end %>

<%= paginate @thoughts %>

app/views/thoughts/dashboard.html.erb
<h1>Deep Thoughts</h1>

<%= simple_form_for @thought do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.input :photo %>
  <%= f.input :tag_list, label: "Tags", hint: "Enter separated by comma" %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>



<%= render partial: 'thoughts' %>